export const defaultParams = {
  yaw: 0,
  pitch: 0,
  faceWidth: 170,
  faceHeight: 170,
  lowerFaceWidth: 145,
  lowerFaceHeight: 126,
  lowerFaceY: 105,
  lowerFaceSideShift: 38,
  outlineArcGap: 1,
  outlineOuterGap: 1,
  outlineInnerGap: 1,
  showGuides: true,
  showHelmet: true,
  showHelmetShell: true,
  showHelmetFacePlate: true,
  showHelmetFarCheekGuard: true,
  showHelmetNearCheekGuard: true,
  showHelmetNoseGuard: true,
  showHairStrands: true,
  showHairPartGuide: true,
  hairRenderMode: "locks",
  hairColor: "#2a241e",
  hairStrandCount: 10,
  hairStrandLength: 85,
  hairStrandThickness: 8,
  hairStrandCurve: 0.55,
  hairStrandSplitCurve: 0,
  hairDownBias: 0.75,
  hairPartPosition: 0,
  hairPartDepth: 1,
  hairline: 1,
  hairlineShape: "rounded",
  hairSideCoverage: 1,
  hairCrownCoverage: 1,
  hairMalePatternBaldnessBias: 0,
  hairBangsBias: 0,
  hairLockCount: 10,
  hairLockWidth: 28,
  hairLockLength: 95,
  hairLockTaper: 0.65,
  hairLockCurve: 0.55,
  hairLockGravity: 0.7,
  hairLockAsymmetry: 0.35,
  hairLockDetailLines: 1,
  eyeSpacing: 46,
  eyeY: -35,
  eyeSize: 18,
  eyeUpperOpen: 1,
  eyeLowerOpen: 1,
  eyeTilt: 0,
  noseLength: 48,
  mouthWidth: 70,
  smile: 0
};

export const sliderConfig = {
  yaw: [-1, 1, 0.01],
  pitch: [-0.5, 0.5, 0.01],
  faceWidth: [120, 220, 1],
  faceHeight: [120, 220, 1],
  lowerFaceWidth: [80, 190, 1],
  lowerFaceHeight: [60, 150, 1],
  lowerFaceY: [55, 145, 1],
  lowerFaceSideShift: [0, 100, 1],
  outlineArcGap: [0.25, 1.8, 0.01],
  outlineOuterGap: [0.25, 1.8, 0.01],
  outlineInnerGap: [0.25, 1.8, 0.01],
  eyeSpacing: [25, 70, 1],
  eyeY: [-75, 20, 1],
  eyeSize: [8, 30, 1],
  eyeUpperOpen: [0.1, 2, 0.01],
  eyeLowerOpen: [0.1, 2, 0.01],
  eyeTilt: [-0.6, 0.6, 0.01],
  noseLength: [20, 80, 1],
  mouthWidth: [30, 110, 1],
  smile: [-35, 35, 1],
  hairStrandCount: [0, 100, 1],
  hairStrandLength: [30, 150, 1],
  hairStrandThickness: [2, 40, 1],
  hairStrandCurve: [0, 1.5, 0.01],
  hairStrandSplitCurve: [0, 1, 0.01],
  hairDownBias: [0, 1, 0.01],
  hairPartPosition: [-1, 1, 0.01],
  hairPartDepth: [0.2, 1.2, 0.01],
  hairline: [0.15, 1, 0.01],
  hairSideCoverage: [0, 1, 0.01],
  hairCrownCoverage: [0, 1, 0.01],
  hairMalePatternBaldnessBias: [0, 1, 0.01],
  hairBangsBias: [0, 1, 0.01],
  hairLockCount: [0, 36, 1],
  hairLockWidth: [8, 70, 1],
  hairLockLength: [30, 190, 1],
  hairLockTaper: [0.1, 1, 0.01],
  hairLockCurve: [0, 1.5, 0.01],
  hairLockGravity: [0, 1, 0.01],
  hairLockAsymmetry: [0, 1, 0.01],
  hairLockDetailLines: [0, 3, 1]
};

export const selectConfig = {
  hairRenderMode: [
    ["locks", "Locks"],
    ["strands", "Strands"],
    ["hybrid", "Hybrid"]
  ],
  hairlineShape: [
    ["rounded", "Rounded"],
    ["straight", "Straight"],
    ["widowsPeak", "Widow's peak"],
    ["receding", "Receding"]
  ]
};

export const colorConfig = {
  hairColor: true
};

export const toggleConfig = {
  showGuides: true,
  showHelmet: true,
  showHelmetShell: true,
  showHelmetFacePlate: true,
  showHelmetFarCheekGuard: true,
  showHelmetNearCheekGuard: true,
  showHelmetNoseGuard: true,
  showHairStrands: true,
  showHairPartGuide: true
};
